package com.ktinsta.server.constants

enum class ResponseConstants(val value: String) {
    SUCCESS("success"),
    USERNAME_UNAVAILABLE("USR_001"),
    INVALID_USER_ID("USR_002"),
    INVALID_USERNAME("USR_003"),
    INVALID_PASSWORD("USR_004"),
    INVALID_EMAIL("USR_005"),
    INVALID_USERNAME_SYMBOLS("USR_006"),
    INVALID_PASSWORD_SYMBOLS("USR_007"),
    TOO_SHORT_USERNAME("USR_008"),
    TOO_LONG_USERNAME("USR_009"),
    TOO_SHORT_PASSWORD("USR_010"),
    TOO_LONG_PASSWORD("USR_011"),
    EMPTY_STATUS("USR_012")
}
