name: Gradle Build

on:
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  run-test-job:
    runs-on: ubuntu-latest

    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: messenger-api
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build & Test with Gradle
        run: ./gradlew test -i
